config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
	root "project#index"
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index', to: 'home#index'
  get 'project/welcome', to: 'project#welcome', as: :welcome
  get 'project/index', to: 'project#index', as: :index
  get "project/new", to:"project#new", as: :new_project
  post 'project/:id', to: 'project#create'
  get 'project/:id', to: 'project#show', as: :project
  get 'project/:id/edit', to: 'project#edit', as: :edit_project
  patch 'project/:id', to: 'project#update', as: :update1
  delete 'project/:id', to: 'project#destroy' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_one :mvc
	has_many :filedets
	has_many :repositories
	validates :name, presence:true
	validates :github_url, presence:true
	# validates :name, uniqueness: true
	validates_uniqueness_of :name
	# validates :github_url, :format => { :with =>/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix,:multiline => true, :message => "invalid git_hub url" }
end

app/controllers/project_controller.rb
require "git"
require 'find'
require 'squid'
require 'uri'
require 'Date'
require 'Rugged'
require 'linguist'
require 'charlock_holmes'

class ProjectController < ApplicationController
  def welcome

  end
 def index
   if user_signed_in?
     puts current_user.id
     @projects = current_user.projects              #assigning current user projects
   end
 end
 def show
      @project = Project.find(params[:id])
     @mvc = @project.mvc
     @technologies = @project.repositories    #assigning project related repository
     @filedets = @project.filedets           #assigning project related stats
     @yes = @project.created_at.strftime("#{@project.created_at.day}-%B-%Y")   #sending data to show.html.erb through @yes as date
                                    #creating a pie chart imaage for displaying in pdf
     config = """{
       type: 'pie',
       data: {
       labels: ['model', 'view', 'controller'],
       datasets: [{
       label: 'Data',
       data: [#{@mvc.models_count},#{@mvc.views_count},#{@mvc.controllers_count}]
       }]
     }
    }"""
    encoded = URI.encode_www_form_component(config.strip)
    # Output a URL to my image
    @hello = "https://quickchart.io/chart?c=#{encoded}" 
    puts @mvc.controllers_count
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render template: "project/edit.html.erb",            #rendering pdf file through view
        layout: 'pdf.html.erb',
        pdf: "#{@project.name}",
        disposition: 'attachment'                            #providing  downloading option
        return
      end
    end
  end
  def new
    @project = Project.new
    # @mvc = Mvc.new
    # @filedet = Filedet.new
  end
  def edit
     @project = Project.find(params[:id])
     @mvc = Mvc.find(params[:id])
     @technologies = @project.repositories    #assigning project related repository
     @filedets = @project.filedets             #assigning project related stats
     @yes = @project.created_at.strftime("#{@project.created_at.day}-%B-%Y")   #sending data to show.html.erb through @yes as date
     #creating a pie chart imaage for displaying in pdf
     config = """{
       type: 'pie',
       data: {
       labels: ['model', 'view', 'controller'],
       datasets: [{
       label: 'Data',
       data: [#{@mvc.models_count},#{@mvc.views_count},#{@mvc.controllers_count}]
       }]
     }
    }"""
    encoded = URI.encode_www_form_component(config.strip)
    # Output a URL to my image
    @hello = "https://quickchart.io/chart?c=#{encoded}" 
    puts @mvc.controllers_count
    @project = Project.find(params[:id])
    respond_to do |format|                                    
      format.html
      format.pdf do
        render template: "project/edit.html.erb",            #rendering pdf file through url
        layout: 'pdf.html.erb',
        pdf: "#{@project.name}",
        disposition: 'attachment'
        return
      end
    end
  end
  def create                      
    # @projects = Project.all
    @project = Project.new(project_params)
    @mvc = Mvc.new(mvc_params)
    @project.user_id = current_user.id
    # cloning project in required directory
    if Project.exists?(github_url: params["github_url"])                        #checking whether url if already exist 
        puts "helllllooooooo"
         flash[:alert] = "project alredy cloned with in db"
          redirect_to new_project_path
          return
    end
      if Project.exists?(name: params["name"])                                #checking whether name is already exist
        puts "helllllooooooo"
        flash[:alert] = "name already exist"
          redirect_to new_project_path
          return
      end
    begin
     Git.clone(params["github_url"],params["name"].to_s , :path => './public/')       #error handling 
    rescue
      if !params["name"].present? && !params["github_url"].present?              #field validations
        flash[:alert] = "fields can't be empty"
      elsif !params["name"].present?
         flash[:alert] = "please enter name"
      elsif !params["github_url"].present?
         flash[:alert] = "url can'be empty"
      else
          flash[:alert] = "invalid url"
      end
      redirect_to new_project_path
      return
    end
    respond_to do |format|
      if @project.save       #saving each project
      #getting technogies used in the repository
      repo = Rugged::Repository.new("./public/#{@project.name}")
      project = Linguist::Repository.new(repo, repo.head.target_id)     #=> "Ruby"
      arr = project.languages
      @limit = arr.length - 1 
      for i in 0..@limit
        @technology = Repository.new(repository_params)           #saving technology names
        @technology.technology_name = arr.keys[i]
        arr1 = Array.new    
        text_file = Array.new  
        arr2 = Array.new                                
        if arr.keys[i] == "Ruby"  
          if (File.exist?("#{Rails.root}/public/#{@project.name}/Gemfile"))                                  #checking Ruby version
            File.open("#{Rails.root}/public/#{@project.name}/Gemfile","r") do |f|                            #getting version from the Gemfile
              f.each_line do |line|
                arr1 = line.split(' ')
                arr1.each do |word|
                  if word == "ruby"
                    @words = word
                    arr2 = line.split(' ')
                    for i in 0..arr2.length-1
                      if arr2[i] == "ruby"
                        @ruby_version =  arr2[i+1]
                        @ruby = @ruby_version.delete_prefix("'").delete_suffix("'")
                      end
                    end
                   break
                  end
                end
              end
              break
            end
          end
        elsif arr.keys[i] == "PHP"                                                                              #checking PHP version
          if (File.exist?("#{Rails.root}/public/#{@project.name}/composer.json"))
            File.open("#{Rails.root}/public/#{@project.name}/composer.json","r") do |f|
              f.each_line do |line|
                arr1 = line.split(' ')
                arr1.each do |word|
                  text_file << word
                end  
              end
            end
          elsif (File.exist?("#{Rails.root}/public/#{@project.name}/web/composer.json"))
            File.open("#{Rails.root}/public/#{@project.name}/web/composer.json","r") do |f|
              f.each_line do |line|
                arr1 = line.split(' ')
                arr1.each do |word|
                  text_file << word
                end  
              end
            end
          else
            @ruby = "-"
          end
          if text_file != []
            for i in 0..text_file.length
              if text_file[i] == '"php":'
                @ruby_version =  text_file[i+1]
                @ruby = @ruby_version.delete_prefix('">=').delete_suffix('",')
              end
            end
          end
        elsif arr.keys[i] == "Python"                                                                        #checking Python version
          File.open("#{Rails.root}/public/#{@project.name}/setup.py","r") do |f|
            f.each_line do |line|
              arr1 = line.split(' ')
              arr1.each do |word|
                text_file << word
              end  
            end
          end
          for i in 0..text_file.length
            if text_file[i] == "<"
              @ruby_version =  text_file[i+1]
              @python = @ruby_version.delete_prefix("'").delete_suffix('",')
              @ruby =  @python.delete_suffix("'")
            end
          end
        elsif arr.keys[i] == "Java"                                                                           #checking java version
          if (File.exist?("#{Rails.root}/public/#{@project.name}/build.gradle"))
            File.open("#{Rails.root}/public/#{@project.name}/build.gradle","r") do |f|
              f.each_line do |line|
                arr1 = line.split(' ')
                arr1.each do |word|
                  text_file << word
                end  
              end
            end
            for i in 0..text_file.length
              if text_file[i] == "sourceCompatibility"
                @ruby_version =  text_file[i+2]
                @ruby = @ruby_version.delete_prefix("JavaVersion.VERSION_")
              end
            end
          elsif (File.exist?("#{Rails.root}/public/#{@project.name}/complete/build.gradle"))
            File.open("#{Rails.root}/public/#{@project.name}/complete/build.gradle","r") do |f|
              f.each_line do |line|
                arr1 = line.split(' ')
                arr1.each do |word|
                  text_file << word
                end  
              end
            end
            if text_file != []
              for i in 0..text_file.length
                if text_file[i] == "sourceCompatibility"
                  @ruby =  text_file[i+2]
                end
              end
            end
          else
            @ruby = "-"
          end
        else
          @ruby = "-"
        end
        @technology.version = @ruby 
        @technology.project_id = @project.id
        @technology.save                                                           #saving repository technologies and versions
      end
      @mvc.project_id = @project.id
      @arr = @project.name                                    
      @ary1 = Dir["#{Rails.root}/public/#{@arr}/***/controllers/**/**.**"].map do |m|                #saving controller stats
        m.chomp('*.**').camelize.split("::").last
      end
      @mvc.controllers_list = @ary1
      @mvc.controllers_count = @ary1.count
      @ary2 = Dir["#{Rails.root}/public/#{@arr}/***/models/**/**.**"].map do |m|                     #saving model stats
        m.chomp('*.**').camelize.split("::").last

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/_form.html.erb
<h1>Clone Project</h1>
  <%= form_with(model: @projects) do |form| %>
  <div>
    <%= form.label :Project_name %><br>
    <%= form.text_field :name %>
    <% @project.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>
  <div>
    <%= form.label :enter_URL %><br>
    <%= form.text_field :github_url %>
</div>
<div class="actions">
    <%= form.submit "clone" %>
 </div>
 <% end %>

app/views/project/edit.html.erb
<% if user_signed_in? %>
<header>
  <center><b><h1 style="color: white; background-color: olive"><%= @project.name %></h1></b></center>
  <h4 style="text-align: right; "><b><%= @yes %></b></h4>
  <h2>
 </header>
 
 <table class= "myTable" style="width: 100%">
  	<tr>
      <th>Models</th>
      <th>Views</th>
      <th>Controllers</th>
  </tr>
  <tr>
      <td><%= @mvc.models_count %></td>
       <td><%= @mvc.views_count %></td>
       <td><%= @mvc.controllers_count %></td>
   </tr>
   </table>    
  <%= image_tag @hello %> 
  <table class= "myTable" style="width: 100%">
  	<tr>
  		<th><b>File name</b></th>
  		<th><b>No.of Lines</b></th>
  		<th><b>No.of Words</b></th>
  		<th><b>No.of Spaces</b></th>
  		<th><b>No.of Letters</b></th>
  	</tr>
  	<% @filedets.each do |file| %>
  	<tr>
  	    <td><%= file.file_name %></td>
  	    <td><%= file.lines_count %></td>
  	    <td><%= file.words_count %></td>
  	    <td><%= file.spaces_count %></td>
  	    <td><%= file.letter_count %></td>
  	</tr>
  	<% end %>
  </table><br>
<table class= "myTable" style="width: 100%">
 <tr>
      <th><b>Technologies</b></th>
      <th><b>Version</b></th>
 </tr>
 <% @technologies.each do |file| %>
 <tr>
        <td><%= file.technology_name %></td>
         <td><%= file.version %></td>
  </tr>
  <% end %>
</table>
<% end %>
<style>
.myTable { 
  width: 100%;
  text-align: left;
  background-color: white;
  border-collapse: collapse; 
  }
.myTable th { 
  background-color: lightblue;
  color: salmon; 
  }
.myTable td, 
.myTable th { 
  padding: 10px;
  border: 1px solid black; 
  }
  tr:nth-child(even) {background-color: #F0ffff;}
</style>

app/views/project/index.html.erb
<nav class="navbar navbar-light " style="background-color: #e3f2fd;">
    <a class="navbar-brand">Test Task</a>
    <% if user_signed_in? %>
        <form class="form-inline nav-item nav-link mr-sm-2">
        	<strong><%= current_user.email %></strong>&nbsp
          &nbsp<%= link_to " Edit profile", edit_user_registration_path %>&nbsp
          &nbsp<%= link_to " logout", destroy_user_session_path, method: :delete %>
        </form>
    <% else %>
        <form class="form-inline">
            <a class="nav-item nav-link mr-sm-2" href="/admins/sign_in">Admin Login</a>
            <a class="nav-item nav-link mr-sm-2" href="/users/sign_in">User Login</a>
            <a class="nav-item nav-link mr-sm-2" href="/users/sign_up">Register</a>
        </form>
    <% end %>
</nav><br>
<% if user_signed_in? %>
<center>
<table class= "myTable" style="width: 90%">
    <tr>
      <th>Project name</th>
      <th>No of Models</th>
      <th>No of Views</th>
      <th>No of Controllers</th>
      <th>View stats</th>
      <th>Export PDF</th>
  </tr>
  <% @projects.each do |project| %>
  <tr>
      <td><%= project.name %></td>
       <td><%= project.mvc.models_count rescue 0 %></td>
       <td><%= project.mvc.views_count rescue 0 %></td>
       <td><%= project.mvc.controllers_count rescue 0 %></td>
       <td><%= link_to "view", project %></td>
       <td><%= link_to "download", project_path(format: :pdf, id: project.id) %></td>
   </tr>
   <% end %>
   </table>    
</center><br>
<center><a href="project/new"><button type="button" class="btn btn-primary">Clone Project</button></center>
<% end %>
<style>
.myTable { 
  width: 100%;
  text-align: left;
  background-color: white;
  border-collapse: collapse; 
  }
.myTable th { 
  background-color: lightblue;
  color: salmon; 
  }
.myTable td, 
.myTable th { 
  padding: 10px;
  border: 1px solid black; 
  }
  tr:nth-child(even) {background-color: #F0ffff;}
</style>

app/views/project/new.html.erb
<nav class="navbar navbar-light " style="background-color: #e3f2fd;">
    <a class="navbar-brand">Test Task</a>
    <% if user_signed_in? %>
        <form class="form-inline nav-item nav-link mr-sm-2">
          <%= link_to "projects", root_path %>&nbsp
        	&nbsp<strong><%= current_user.email %></strong>&nbsp
          &nbsp<%= link_to " Edit profile", edit_user_registration_path %>&nbsp
          &nbsp<%= link_to " logout", destroy_user_session_path, method: :delete %>
        </form>
    <% else %>
        <form class="form-inline">
            <a class="nav-item nav-link mr-sm-2" href="/admins/sign_in">Admin Login</a>
            <a class="nav-item nav-link mr-sm-2" href="/users/sign_in">User Login</a>
            <a class="nav-item nav-link mr-sm-2" href="/users/sign_up">Register</a>
        </form>
    <% end %>
</nav>
<% if user_signed_in? %>
<div class="hello">
<%= render 'form', projects: @project %>
 <%= link_to 'Back', root_path %>
</div>
 <% end %>
 <style>
  .hello{
    content: center;
    padding-left: 40%;
    background-color: lightyellow;
  }
</style>

app/views/project/show.html.erb
<% if user_signed_in? %>
<header>
  <center><b><h1 style="color: white; background-color: olive"><%= @project.name %></h1></b></center>
  <h4 style="text-align: right; "><b><%= @yes %></b></h4>
  <h2>
 </header>
 <table class= "myTable" style="width: 100%">
  	<tr>
      <th>Models</th>
      <th>Views</th>
      <th>Controllers</th>
  </tr>
  <tr>
      <td><%= @mvc.models_count %></td>
       <td><%= @mvc.views_count %></td>
       <td><%= @mvc.controllers_count %></td>
   </tr>
   </table>    
  <%= image_tag @hello %> 
  <table class= "myTable" style="width: 100%">
  	<tr>
  		<th><b>File name</b></th>
  		<th><b>No.of Lines</b></th>
  		<th><b>No.of Words</b></th>
  		<th><b>No.of Spaces</b></th>
  		<th><b>No.of Letters</b></th>
  	</tr>
  	<% @filedets.each do |file| %>
  	<tr>
  	    <td><%= file.file_name %></td>
  	    <td><%= file.lines_count %></td>
  	    <td><%= file.words_count %></td>
  	    <td><%= file.spaces_count %></td>
  	    <td><%= file.letter_count %></td>
  	</tr>
  	<% end %>
  </table><br>
<table class= "myTable" style="width: 100%">
 <tr>
      <th><b>Technologies</b></th>
 </tr>
 <% @technologies.each do |file| %>
 <tr>
        <td><%= file.technology_name %></td>
  </tr>
  <% end %>
</table>
<% end %>
<style>
.myTable { 
  width: 100%;
  text-align: left;
  background-color: white;
  border-collapse: collapse; 
  }
.myTable th { 
  background-color: lightblue;
  color: salmon; 
  }
.myTable td, 
.myTable th { 
  padding: 10px;
  border: 1px solid black; 
  }
  tr:nth-child(even) {background-color: #F0ffff;}
</style>

app/views/project/welcome.html.erb
<nav class="navbar navbar-light " style="background-color: #e3f2fd;">
    <a class="navbar-brand">Test Task</a>
    <% if user_signed_in? %>
        <form class="form-inline nav-item nav-link mr-sm-2">
          <%= link_to "projects", root_path %>&nbsp
        	&nbsp<strong><%= current_user.email %></strong>&nbsp
          &nbsp<%= link_to " Edit profile", edit_user_registration_path %>&nbsp
          &nbsp<%= link_to " logout", destroy_user_session_path, method: :delete %>
        </form>
    <% else %>
        <form class="form-inline">
            <a class="nav-item nav-link mr-sm-2" href="/admins/sign_in">Admin Login</a>
            <a class="nav-item nav-link mr-sm-2" href="/users/sign_in">User Login</a>
            <a class="nav-item nav-link mr-sm-2" href="/users/sign_up">Register</a>
        </form>
    <% end %>
</nav><br>
<% if user_signed_in? %>
<center><b><h1>welcome</h1></b></center>
<% end %>